### ISSUE TITLE
Import error . The following line is showing error when run locally

### ISSUE THREAD

**Issue by namanbiyani** [torchgan/torchgan#107]
[This](https://github.com/torchgan/torchgan/blob/a9f28fda26c911a94b76bf473917b028aa5807d6/torchgan/models/autoencoding.py#L7) line is showing error when torchgan is run locally . Should I change it to 
`from .models import Discriminator, Generator`
as in other files like acgan.py

**Comment by avik-pal** [comment]
@namanbiyani yes please do it
