### ISSUE TITLE
How to cite?

### ISSUE THREAD

**Issue by dsevero** [torchgan/torchgan#111]
I've been using this project the last couple of weeks to run the experiments for a paper I'm writing.
I was wondering how exactly I could cite it.

https://help.github.com/en/articles/referencing-and-citing-content

**Comment by avik-pal** [comment]
@dsevero We are working on a technical report for the software and aim to release a preprint on arxiv by the end of next week.

**Comment by avik-pal** [comment]
A small update, we have submitted the paper to arxiv and it should be available by Monday 20:00 EDT. Will post the link then.

**Comment by dsevero** [comment]
Oh, I'm actually going to submit my paper tomorrow.

I can reference the repo. for now and update it on later on. What do you think @avik-pal ?

**Comment by avik-pal** [comment]
@dsevero 	That works too. But in case you haven't already submitted your paper, our [paper](https://arxiv.org/abs/1909.03410) is now available. Its BibTeX is

```
@misc{pal2019torchgan,
    title={{TorchGAN: A Flexible Framework for GAN Training and Evaluation}},
    author={Avik Pal, and Aniket Das},
    year={2019},
    eprint={1909.03410},
    archivePrefix={arXiv},
    primaryClass={cs.LG}
}
```
