### ISSUE TITLE
Mistake in CycleGAN tutorial about identity loss

### ISSUE THREAD

**Issue by toooldtoohard** [torchgan/torchgan#125]
In CycleGAN Tutorial.ipynb, the description and code about identity loss are wrong.
Current code is :
fake_a = gen_b2a(image_b)
fake_b = gen_a2b(image_a)
loss_identity = 0.5 * (F.l1_loss(fake_a, image_a) + F.l1_loss(fake_b, image_b))

The correct code should be:
loss_identity = 0.5 * (F.l1_loss(gen_b2a(image_a), image_a) + F.l1_loss(gen_a2b(image_b), image_b))

**Comment by avik-pal** [comment]
`gen_a2b` means it converts `image_a` to `image_b`. The same holds true for `gen_b2a`. The current definition seems to be consistent across all the losses used in the tutorial.

**Comment by toooldtoohard** [comment]
Dear avik-pal, I'm pretty sure it's a mistake about identity loss, you can refer to the source code delivered by the author of Cyclegan:
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/blob/master/models/cycle_gan_model.py
and it's consistent with the explanation  of 'identity' in the Cyclegan paper.
Anyway, thanks for your excellent work and the torchgan framework really help me a lot:)
