### ISSUE TITLE
Two Time-Step Update Rule

### ISSUE THREAD

**Issue by PasqualeZingo** [torchgan/torchgan#133]
I cannot find any reference to TTUR in the documentation (see more about the technique here https://arxiv.org/abs/1706.08500).  Would it be possible to implement it for WGAN-GP for torchgan?  I'm new to the framework but I think the right place to implement it would be in  torchgan.losses.WassersteinGradientPenalty.

**Comment by avik-pal** [comment]
@PasqualeZingo Were you able to find the solution?

Just FYI, TTUR is already implemented [here](https://torchgan.readthedocs.io/en/latest/modules/trainer.html#trainer). Discriminators and Generators use their own optimizers so the user can just use different learning rates.
