### ISSUE TITLE
AttributeError while trying to use torchgan.layers.VirtualBatchNorm

### ISSUE THREAD

**Issue by Sabian98** [torchgan/torchgan#135]
I am getting the error **AttributeError: 'VirtualBatchNorm' object has no attribute 'weight'** while using the module to implement virtual batch normalization. For the context, here is my weights_init function:
`    

def weights_init(m):
	classname = m.__class__.__name__
	print(classname)
	if classname.find('Conv') != -1:
		nn.init.normal_(m.weight.data, 0.0, 0.02)
	elif classname.find('BatchNorm') != -1:
		nn.init.normal_(m.weight.data, 1.0, 0.02)
		nn.init.constant_(m.bias.data, 0)`
python version -3.7.4
pyTorch version-1.5.0

**Comment by avik-pal** [comment]
`classname.find('BatchNorm')` will return != -1 for `VirtualBatchNorm`. I would suggest changing that line to `classname.find('BatchNorm') != -1 and classname.find('VirtualBatchNorm') == -1`.

**Comment by Sabian98** [comment]
It worked. Thanks a bunch
