### ISSUE TITLE
JOSS Review: Code coverage

### ISSUE THREAD

**Issue by NMontanaBrown** [torchgan/torchgan#138]
# Issue Description

I am reviewing the JOSS submission linked to this repository, see: [Joss Review](https://github.com/openjournals/joss-reviews/issues/2606)

Running

```bash
python -m pytest --cov=torchgan /tests --cov-report term-missing
```

showcases that the test coverage for the losses module for the repository is quite low. Are you planning on expanding your loss test cases? I think this is important for this type of package as it drives the model training, and is such linked to the checkbox "functionality" for the review.

**Comment by avik-pal** [comment]
Yes, I do plan to extend the code cov for the loss module

**Comment by avik-pal** [comment]
I have updated the master branch with integration tests for the losses module.
