### ISSUE TITLE
Pytorch version

### ISSUE THREAD

**Issue by sixin-zh** [torchgan/torchgan#144]
Hello,  I have got a torchgan base with version v0.0.4. Which version of pytorch should be used? I did not find any documentation on this. 

best,
Sixin

**Comment by avik-pal** [comment]
Any particular reason to not use v0.1.0?

**Comment by sixin-zh** [comment]
I am not sure  of their differences, but I'll give a try.  For the sake of reproducing the scientific results which is based on the older version of the code, in case you know the right version, please let me know ...  I tried pytorch 0.4.1 and 1.2.0, they do not work on the version v.0.0.4 ...

**Comment by sixin-zh** [comment]
Hi, I just tried 1.9.0 and it works. So it's better to use more recent version of pytorch ...
