### ISSUE TITLE
GAN Models

### ISSUE THREAD

**Issue by Aniket1998** [torchgan/torchgan#2]
List of GAN Models we want to have before __v0.1__

- [x] DCGAN
- [x] Conditional GAN
- [x] Autoencoder Model for EBGAN and BEGAN
- [x] Self Attention GAN

@avik-pal  Add any other models you find relevant.

**Comment by avik-pal** [comment]
Self Attention GAN as decided will not be put inside the `models` module. The necessary building blocks in the `layers` module make it easy enough to design the SAGAN.
