### ISSUE TITLE
Fix coverage

### ISSUE THREAD

**Issue by avik-pal** [torchgan/torchgan#51]
The coverage results I have tested locally are around 70% but in travis they seem to be reported as low as 22%. Apparently none od the files inside `torchgan` are being covered.

**Comment by namanbiyani** [comment]
Hi , I would like to solve this issue . Could you please give some guidelines ?

**Comment by avik-pal** [comment]
The first thing I would do would be to check if the travis script is correct. [This line](https://github.com/torchgan/torchgan/blob/ba28c868880040174a12aeed22afddafcb1836e3/.travis.yml#L25) when run locally and when on travis gives completely different results.

Might be worth how other similar repositories like [ignite](https://github.com/pytorch/ignite/blob/master/.travis.yml) do it. You can try refactoring our script and see if it works.
