### ISSUE TITLE
Fix Gradient Visualization

### ISSUE THREAD

**Issue by avik-pal** [torchgan/torchgan#63]
Currently, instead of displaying the `gradients` norm we are showing the norm of the model `parameters.`
Problems in fixing this simply:
1. We are clearing the gradient buffers every time; this makes it impossible to track gradients for different losses.
2. Printing the gradient wrt only the last executed loss will lead to wrong inference on the part of the user.
3. Can't make gradients a property of the loss as it makes custom losses a nightmare to implement (we will have to impose a lot of constraints).

**Comment by Aniket1998** [comment]
This can be fixed by storing the gradients of each parameter after going through the train_ops of each loss (as the gradient buffers are zeroed out at the beginning and not at the end). Will submit a PR once #62 is merged.
