### ISSUE TITLE
Windows 10 installation not working

### ISSUE THREAD

**Issue by bosaving** [torchgan/torchgan#78]
Can torchgan be installed for win10 ?
Are there ways to install torchgan in win10 ? I installed anaconda 3-4.2.0 with python3.5, tensorflow, torch and torchvision.

**Comment by avik-pal** [comment]
@bosaving you can now use conda for installation
`conda install -c avik-pal torchgan  `

**Comment by bosaving** [comment]
> @bosaving you can now use conda for installation
> `conda install -c avik-pal torchgan `

It does not work.
PackagesNotFoundError: The following packages are not avaible from current channels:
-torchgan
-torchvison
-torchgan
-pytorch

My anaconda is anaconda3-4.2.0-win-X64, python is 3.5.2, without GPU, operating system is win10 family.

**Comment by avik-pal** [comment]
@Aniket1998 can you have a look at this?

**Comment by avik-pal** [comment]
@bosaving I have added an appveyor build which is working fine. So FWIW torchgan is working on Windows. Closing this issue.
