### ISSUE TITLE
Epoch Time duration should be printed in epoch summary

### ISSUE THREAD

**Issue by namanbiyani** [torchgan/torchgan#95]
The time duration of running of epoch of epoch should be printed in epoch summary as it happens in tensorflow . Please tell which files i would need to change , I would like to work on this.

**Comment by avik-pal** [comment]
This would be an interesting feature to have. The easiest way would be to integrate [fastprogress](https://github.com/fastai/fastprogress) with torchgan trainer. You will have to change the part where we are iterating over the Data Loader.
